### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by rmessett15** [eeast/GP1-FrontEndApplication#11]
About us (entire HTML page)
Rotating Carousel

Primary: Photo, brief about me, links to github and linkedin
Inputs: none
Outputs: none

**Comment by elizabetholsavsky** [comment]
About us page has been created and pushed in feature/about. 

Page will need to be updated with consistent styles, team member photos, links, and short bios.

***Materialize folder is included because it was needed to create carousel. Can be added with asset files or deleted/repath html if already included elsewhere. 

Notes to consider for team review on Monday:
        -js and style tags included to minimize conflict, can be moved to respective sheets after merge
        -need to consider responsiveness, do we want to maintain carousel on mobile or use cards?
        -do we want to use icons? if so, should we stick with one icon library?
        -need image folder, each team member can insert own image for carousel
        -what information about our project/process do we want to highlight in the description?
        -how do we want navbar to look/function?

**Comment by elizabetholsavsky** [comment]
All group members photos appear with links to personal github account. Project repo linked in project description.
Page functional and styled with mobile responsiveness.
