### ISSUE TITLE
Outline Project Code

### ISSUE THREAD

**Issue by eeast** [eeast/GP1-FrontEndApplication#3]
To help with segmentation of code, comments should ideally outline the basic workflow of the website. What sections we'll have in the HTML, what functions we'll need in the JS, etc. Once we have the outline set up, it will be much easier to fill in the code and have it work together when finished.

Example comment:
HTML

JS
/* Function: exampleFunction()
    Arguments: ...
    Returns: ...
    Function: ...
*/

**Comment by elizabetholsavsky** [comment]
I agree with you that comments are great place to start. I asked my tutor for general advice for the project and he said to be sure to create a wireframe and design outline first and then add/connect functionality. (Generally just to have a solid plan to build from because it will make collaboration smoother). Comments will hopefully help us avoid working in the same area/merge conflicts.

**Comment by eeast** [comment]
![Image](https://user-images.githubusercontent.com/32493618/225189094-78816c86-631f-4778-ad02-0d86315ed2b6.png)

**Comment by HunterHester** [comment]
Completed
